[build]
  functions = "netlify/functions"
  publish = "/" # Ou le répertoire où se trouve ton site HTML

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"